fix lint errors and warnings
TaskarCenterAtUW/TDEI-template-datasvc-ts pull request #39
Opened 2023-06-17 18:38 UTC by iAKM

2023-06-18 13:39 UTC, sureshgaussian requested changes
mention if the unit tests passed in your local machine in the PR description.

2023-06-26 13:09 UTC, sureshgaussian commented
@iAKM The branch has conflicts. Please resolve them. Also, the unit tests are not passing on my local machine. 
@MashB FYI!

2023-09-13 07:14 UTC, susrisha approved these changes

2023-09-13 07:16 UTC, MashB approved these changes

2023-09-13 18:09 UTC, sureshgaussian approved these changes
spot checked the code and approving.

2023-09-13 18:40 UTC, merged